version: "3.8"
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: myapp_frontend_c
    volumes:
      - /app/node_modules
      - .:/app
    ports:
      - '3000:3000'
  test: 
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - /app/node_modules
    command: ["npm", "run", "test"]
